In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\ricky\\Code\\SciP\\content\\mini_scRNA_example.csv')
df.head()

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6

In [3]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [4]:
print(df.shape)

(16, 13)

In [5]:
df.shape[1]

13

In [ ]:
print(df.index)

In [ ]:
print(df.columns)

In [ ]:
print(df.dtypes)

In [ ]:
a = [1, 3, 4, 5]
print(a[:3])

In [ ]:
print(df['TJP1'][2:6])

In [ ]:
print(df['TJP1'] * 5)

In [ ]:
df['express_diff'] = df['EPCAM'] - df['CD3D']

In [ ]:
df

In [ ]:
del df['express_diff']

In [ ]:
df

In [6]:
df_part = df.iloc[[2,4,5],:5]
df_part

   Cell_ID  Sample_ID Condition   Cell_Type  EPCAM
2  Cell_03  Control_2   Control  Epithelial     15
4  Cell_05   Celiac_1    Celiac  Epithelial     12
5  Cell_06   Celiac_1    Celiac  Epithelial     10

In [ ]:
df_part = df.iloc[:3,:3]
df_part

In [ ]:
df.iloc[:3,[0, 7, 3]]

In [ ]:
df.iloc[[8, 5, 4],[0, 7, 3]]

In [ ]:
# 只有loc函数的冒号slicing，会将结束的index包含在内
df.loc[0:5,'Cell_ID': 'Cell_Type']

In [ ]:
df.loc[[10, 8, 5, 3],'Cell_ID': 'Cell_Type']

In [ ]:
df_record = pd.DataFrame()
df_record['Name'] = ['Alic', 'Bob', 'Cathy']
df_record['Job'] = ['student', 'student', 'Farmer']
df_record

In [ ]:
df_record.index = ['a', 'b', 'c']
df_record

In [ ]:
df_record['salary'] = [10, 100, 1000]
df_record

In [ ]:
df

In [ ]:
df['EPCAM']

In [ ]:
df['EPCAM'] > 12

In [ ]:
df[df['EPCAM'] > 12]

In [ ]:
df[(df['EPCAM'] > 12)&(df['Condition']=='Control')]

In [ ]:
df

In [ ]:
df.sort_values(by='EPCAM', ascending=False)

In [ ]:
df.sort_values(by=['EPCAM','CD3D','MS4A1'], ascending=[False, True, False])

In [ ]:
df.describe()

In [ ]:
df[['CD3D', 'KRT18', 'OCLN']].mean()

In [ ]:
df_nan = pd.read_csv('/content/mini_scRNA_nan.csv')
df_nan

In [ ]:
df_nan.describe()

In [ ]:
df_nan['IFNG'].isna()

In [ ]:
df.corr()

In [ ]:
df[['EPCAM', 'KRT18', 'CD3D', 'MS4A1', 'LST1', 'IFNG', 'CXCL10', 'OCLN', 'TJP1']].corr()

In [2]:
import numpy as np

In [ ]:
a_list = [14,24,34,44]

In [ ]:
a=np.array(a_list)

In [ ]:
a

In [ ]:
a+3

In [ ]:
b=np.array([100,300,500,700])

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

In [ ]:
c_list = [[1,2.0,3],[44,55,66]]
c=np.array(c_list,dtype=complex)
print(c)

In [ ]:
np.arange(0,10,2)

In [ ]:
np.ones([3, 4, 5])

In [ ]:
np.zeros([3,4])

In [ ]:
np.random.randint(0,100,(3,4))

In [ ]:
np.random.normal(100,15,[7,7])
# Normal distribution, avg 100, std diff 15, in 7x7

In [ ]:
np.random.random([5,6])

In [ ]:
a = np.arange(0,24)
print(a)

In [ ]:
a.reshape(4,6)

In [ ]:
a=a.reshape(3,2,2,2)

In [ ]:
a=a.reshape(4,6)
print(a)

In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [8]:
np.vdot(a.reshape(2,2),b.reshape(2,2))

np.int64(70)

In [9]:
np.linalg.norm(a)

np.float64(5.477225575051661)

In [10]:
np.vdot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

np.float64(0.9688639316269662)

In [11]:
np.matmul(a.reshape(2,2),np.arange(6).reshape(2,3))

array([[ 6,  9, 12],
       [12, 19, 26]])

In [12]:
d = np.arange(6).reshape(2,3)
print(d)

[[0 1 2]
 [3 4 5]]

In [13]:
d.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
np.transpose(d)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [2]:
import sklearn

In [ ]:
from sklearn import datasets
digits = datasets.load_digits()