In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('C:\\Users\\ricky\\Code\\SciP\\content\\mini_scRNA_example.csv')
df.head()

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6

In [50]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [51]:
print(df.shape)

(16, 13)

In [52]:
df.shape[1]

13

In [53]:
print(df.index)

RangeIndex(start=0, stop=16, step=1)

In [54]:
print(df.columns)

Index(['Cell_ID', 'Sample_ID', 'Condition', 'Cell_Type', 'EPCAM', 'KRT18',
       'CD3D', 'MS4A1', 'LST1', 'IFNG', 'CXCL10', 'OCLN', 'TJP1'],
      dtype='str')

In [55]:
print(df.dtypes)

Cell_ID        str
Sample_ID      str
Condition      str
Cell_Type      str
EPCAM        int64
KRT18        int64
CD3D         int64
MS4A1        int64
LST1         int64
IFNG         int64
CXCL10       int64
OCLN         int64
TJP1         int64
dtype: object

In [56]:
a = [1, 3, 4, 5]
print(a[:3])

[1, 3, 4]

In [57]:
print(df['TJP1'][2:6])

2    13
3    10
4     6
5     5
Name: TJP1, dtype: int64

In [58]:
print(df['TJP1'] * 5)

0     60
1     55
2     65
3     50
4     30
5     25
6     30
7     20
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
Name: TJP1, dtype: int64

In [59]:
df['express_diff'] = df['EPCAM'] - df['CD3D']

In [60]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1,express_diff
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12,14
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11,12
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13,15
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10,11
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6,12
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5,10
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6,13
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4,9
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0,-16
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0,-18
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0,-20
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0,-19
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0,0

In [61]:
del df['express_diff']

In [62]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [63]:
df_part = df.iloc[[2,4,5],:5]
df_part

   Cell_ID  Sample_ID Condition   Cell_Type  EPCAM
2  Cell_03  Control_2   Control  Epithelial     15
4  Cell_05   Celiac_1    Celiac  Epithelial     12
5  Cell_06   Celiac_1    Celiac  Epithelial     10

In [64]:
df_part = df.iloc[:3,:3]
df_part

   Cell_ID  Sample_ID Condition
0  Cell_01  Control_1   Control
1  Cell_02  Control_1   Control
2  Cell_03  Control_2   Control

In [65]:
df.iloc[:3,[0, 7, 3]]

   Cell_ID  MS4A1   Cell_Type
0  Cell_01      0  Epithelial
1  Cell_02      0  Epithelial
2  Cell_03      0  Epithelial

In [66]:
df.iloc[[8, 5, 4],[0, 7, 3]]

   Cell_ID  MS4A1   Cell_Type
8  Cell_09      0      T_cell
5  Cell_06      0  Epithelial
4  Cell_05      0  Epithelial

In [67]:
# 只有loc函数的冒号slicing，会将结束的index包含在内
df.loc[0:5,'Cell_ID': 'Cell_Type']

   Cell_ID  Sample_ID Condition   Cell_Type
0  Cell_01  Control_1   Control  Epithelial
1  Cell_02  Control_1   Control  Epithelial
2  Cell_03  Control_2   Control  Epithelial
3  Cell_04  Control_2   Control  Epithelial
4  Cell_05   Celiac_1    Celiac  Epithelial
5  Cell_06   Celiac_1    Celiac  Epithelial

In [68]:
df.loc[[10, 8, 5, 3],'Cell_ID': 'Cell_Type']

    Cell_ID  Sample_ID Condition   Cell_Type
10  Cell_11   Celiac_1    Celiac      T_cell
8   Cell_09  Control_1   Control      T_cell
5   Cell_06   Celiac_1    Celiac  Epithelial
3   Cell_04  Control_2   Control  Epithelial

In [69]:
df_record = pd.DataFrame()
df_record['Name'] = ['Alic', 'Bob', 'Cathy']
df_record['Job'] = ['student', 'student', 'Farmer']
df_record

    Name      Job
0   Alic  student
1    Bob  student
2  Cathy   Farmer

In [70]:
df_record.index = ['a', 'b', 'c']
df_record

    Name      Job
a   Alic  student
b    Bob  student
c  Cathy   Farmer

In [71]:
df_record['salary'] = [10, 100, 1000]
df_record

    Name      Job  salary
a   Alic  student      10
b    Bob  student     100
c  Cathy   Farmer    1000

In [72]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [73]:
df['EPCAM']

0     14
1     12
2     15
3     11
4     12
5     10
6     13
7      9
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
Name: EPCAM, dtype: int64

In [74]:
df['EPCAM'] > 12

0      True
1     False
2      True
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
Name: EPCAM, dtype: bool

In [75]:
df[df['EPCAM'] > 12]

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6

In [76]:
df[(df['EPCAM'] > 12)&(df['Condition']=='Control')]

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13

In [77]:
df

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [78]:
df.sort_values(by='EPCAM', ascending=False)

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0

In [79]:
df.sort_values(by=['EPCAM','CD3D','MS4A1'], ascending=[False, True, False])

,Cell_ID,Sample_ID,Condition,Cell_Type,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
2,Cell_03,Control_2,Control,Epithelial,15,20,0,0,0,0,1,11,13
0,Cell_01,Control_1,Control,Epithelial,14,18,0,0,0,0,1,10,12
6,Cell_07,Celiac_2,Celiac,Epithelial,13,18,0,0,0,0,8,5,6
1,Cell_02,Control_1,Control,Epithelial,12,16,0,0,0,0,0,9,11
4,Cell_05,Celiac_1,Celiac,Epithelial,12,17,0,0,0,0,7,5,6
3,Cell_04,Control_2,Control,Epithelial,11,15,0,0,0,0,0,8,10
5,Cell_06,Celiac_1,Celiac,Epithelial,10,15,0,0,0,0,9,4,5
7,Cell_08,Celiac_2,Celiac,Epithelial,9,14,0,0,0,0,10,3,4
13,Cell_14,Celiac_1,Celiac,B_cell,0,0,0,18,0,1,1,0,0
12,Cell_13,Control_1,Control,B_cell,0,0,0,15,0,0,0,0,0
14,Cell_15,Control_2,Control,Myeloid,0,0,0,0,16,1,2,0,0
15,Cell_16,Celiac_2,Celiac,Myeloid,0,0,0,0,20,3,7,0,0
8,Cell_09,Control_1,Control,T_cell,0,1,16,0,0,4,1,0,0
9,Cell_10,Control_2,Control,T_cell,0,0,18,0,0,5,1,0,0
11,Cell_12,Celiac_2,Celiac,T_cell,0,0,19,0,0,14,5,0,0
10,Cell_11,Celiac_1,Celiac,T_cell,0,1,20,0,0,12,4,0,0

In [80]:
df.describe()

,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000
mean,6.000000,8.437500,4.562500,2.062500,2.250000,2.500000,3.562500,3.437500,4.187500
std,6.345602,8.571027,8.197306,5.662376,6.191392,4.412105,3.558441,4.098272,4.942587
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,4.500000,7.500000,0.000000,0.000000,0.000000,0.000000,1.500000,1.500000,2.000000
75%,12.000000,16.250000,4.000000,0.000000,0.000000,3.250000,7.000000,5.750000,7.000000
max,15.000000,20.000000,20.000000,18.000000,20.000000,14.000000,10.000000,11.000000,13.000000

In [81]:
df[['CD3D', 'KRT18', 'OCLN']].mean()

CD3D     4.5625
KRT18    8.4375
OCLN     3.4375
dtype: float64

In [82]:
df_nan = pd.read_csv('/content/mini_scRNA_nan.csv')
df_nan

FileNotFoundError: [Errno 2] No such file or directory: '/content/mini_scRNA_nan.csv'

In [ ]:
df_nan.describe()

,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
count,16.000000,16.000000,16.000000,15.000000,16.000000,15.000000,16.000000,16.000000,16.000000
mean,6.000000,8.437500,4.562500,2.200000,2.250000,2.333333,3.562500,3.437500,4.187500
std,6.345602,8.571027,8.197306,5.833401,6.191392,4.514527,3.558441,4.098272,4.942587
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,4.500000,7.500000,0.000000,0.000000,0.000000,0.000000,1.500000,1.500000,2.000000
75%,12.000000,16.250000,4.000000,0.000000,0.000000,2.000000,7.000000,5.750000,7.000000
max,15.000000,20.000000,20.000000,18.000000,20.000000,14.000000,10.000000,11.000000,13.000000

In [ ]:
df_nan['IFNG'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
Name: IFNG, dtype: bool

In [ ]:
df.corr()

ValueError: could not convert string to float: 'Cell_01'

In [ ]:
df[['EPCAM', 'KRT18', 'CD3D', 'MS4A1', 'LST1', 'IFNG', 'CXCL10', 'OCLN', 'TJP1']].corr()

,EPCAM,KRT18,CD3D,MS4A1,LST1,IFNG,CXCL10,OCLN,TJP1
EPCAM,1.000000,0.996537,-0.561357,-0.367369,-0.366523,-0.571480,0.162382,0.930554,0.933138
KRT18,0.996537,1.000000,-0.550283,-0.382477,-0.381596,-0.566776,0.218720,0.905183,0.909106
CD3D,-0.561357,-0.550283,1.000000,-0.216250,-0.215752,0.880167,-0.116702,-0.497969,-0.502992
MS4A1,-0.367369,-0.382477,-0.216250,1.000000,-0.141195,-0.172117,-0.329417,-0.325886,-0.329173
LST1,-0.366523,-0.381596,-0.215752,-0.141195,1.000000,-0.034167,0.132385,-0.325136,-0.328415
IFNG,-0.571480,-0.566776,0.880167,-0.172117,-0.034167,1.000000,0.036093,-0.506950,-0.512063
CXCL10,0.162382,0.218720,-0.116702,-0.329417,0.132385,0.036093,1.000000,-0.155142,-0.146644
OCLN,0.930554,0.905183,-0.497969,-0.325886,-0.325136,-0.506950,-0.155142,1.000000,0.999495
TJP1,0.933138,0.909106,-0.502992,-0.329173,-0.328415,-0.512063,-0.146644,0.999495,1.000000

In [84]:
import numpy as np

In [85]:
a_list = [14,24,34,44]

In [86]:
a=np.array(a_list)

In [92]:
a

array([14, 24, 34, 44])

In [88]:
a+3

array([17, 27, 37, 47])

In [91]:
b=np.array([100,300,500,700])

In [94]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[114 324 534 744]
[ -86 -276 -466 -656]
[ 1400  7200 17000 30800]
[0.14       0.08       0.068      0.06285714]

In [95]:
c_list = [[1,2.0,3],[44,55,66]]
c=np.array(c_list,dtype=complex)
print(c)

[[ 1.+0.j  2.+0.j  3.+0.j]
 [44.+0.j 55.+0.j 66.+0.j]]